spring.application.name=CrudSpring
spring.datasource.url=jdbc:oracle:thin:@localhost:1522:XE
spring.datasource.username=system
spring.datasource.password=33161818
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.hibernate.ddl-auto=update